### ISSUE TITLE
Submission `9712751`

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/support#1]
Tool type: Location Annotator
Submission ID: 9712751
Submission Status: ACCEPTED
Submission MCW Status: INVALID
Synapse user: tschaffter

**Comment by tschaffter** [comment]
Hi @gkowalski, the above submission failed on MCW PHI dataset. Could you share by email with me the log that you have? Thanks!

**Comment by gkowalski** [comment]
How do I obtain these again ?

**Comment by thomasyu888** [comment]
@gkowalski Here are the steps:

1. Go to this [view](https://www.synapse.org/#!Synapse:syn25582644/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjI1NTgyNjQ0IiwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1LCAic29ydCI6W3siY29sdW1uIjoiY3JlYXRlZE9uIiwgImRpcmVjdGlvbiI6IkRFU0MifV19) and search for 9712751.  You will find that it has submission id: 9712756.
1. Scroll to the right in that view and look for the `orgSagebionetworksSynapseWorkflowOrchestratorSubmissionFolder` column and download the submission logs in that folder.
1.  Go to the MCW ELK stack and export logs.
1. upload logs and provide access to @tschaffter 

In this scenario after doing step 2, I found that it was an issue with the pipeline not being able to find the container, so this submission needs to be resubmitted.  Can you resubmit @tschaffter ?

**Comment by gkowalski** [comment]
Is exporting all ELT stack logs the norm, or just logs from the date  that the submission was made on more appropriate   ? Also I could limit the export to docker.image:sagebionetworks/synapse-workflow-orchestrator .  Last time I shared these to Conner from a folder in https://www.synapse.org/  . I'll do that going forward. 

I see the first time for conner I only exported the ELK logs. I've not shared the logs from synapse . I'll add the ELK logs today.

**Comment by thomasyu888** [comment]
@gkowalski You don't need to upload that particular zip file, because participants actually have access to that file already.  I think you want to export the ELK stack logs for that particular submission if it exists.  But according to the orchestrator logs, this was an infrastructure issue, so you actually didn't need to do anything.

**Comment by gkowalski** [comment]
Then what does step 2 above for ?

**Comment by thomasyu888** [comment]
I think just exporting the ELK stack logs for that particular submission is appropriate.  The ELK logs will have to be scrubbed just in case if contains any trace of MCW data.  I think the first step is to look at the `sagebionetworks/synapse-workflow-orchestrator` logs then determine whether or not ELK logs need to be uploaded.  Sharing them to a folder on Synapse is perfect.

**Comment by tschaffter** [comment]
@thomasyu888 In my mind the only meaning full logs for the user are the ELK logs. Is that correct? If yes, no need to share the workflow logs, which may be confusing.

**Comment by tschaffter** [comment]
I like the idea of sharing the log with Synapse rather than email for audit purpose.

**Comment by gkowalski** [comment]
done
