### ISSUE TITLE
remove internal IP Exposure 

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/support#10]
### Problem description

Please remove the column MCW_datanode_endpoint from this report as it exposes our internal server IP : 
 

https://www.synapse.org/#!Synapse:syn23633030/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjIzNjMzMDMwIiwgInNlbGVjdGVkRmFjZXRzIjpbeyJjb25jcmV0ZVR5cGUiOiJvcmcuc2FnZWJpb25ldHdvcmtzLnJlcG8ubW9kZWwudGFibGUuRmFjZXRDb2x1bW5WYWx1ZXNSZXF1ZXN0IiwgImNvbHVtbk5hbWUiOiJldmFsdWF0aW9uaWQiLCAiZmFjZXRWYWx1ZXMiOltdfV0sICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNSwgInNvcnQiOlt7ImNvbHVtbiI6ImNyZWF0ZWRPbiIsICJkaXJlY3Rpb24iOiJERVNDIn1dfQ==

**Comment by thomasyu888** [comment]
This is the admin view that is only viewable to us and not to the public.
