### ISSUE TITLE
Log request for submission 9712812

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/support#5]
### Request details

- Tool type (select one)
  - [ x] NLP Sandbox PHI annotator
  - [ ] NLP Sandbox date annotator
  - [ ] NLP Sandbox person name annotator
  - [ ] NLP Sandbox location annotator
  - [ ] NLP Sandbox contact annotator
  - [ ] NLP Sandbox ID annotator
- Submission id:  9712812
- Submitter user/team handle: MCW Team
- Submission status:
  - Column `Status`:
  - Column `MCW Status`
- Requesting logs for the following dataset(s):
  - [x] i2b2-phi
  - [ ] mcw-phi

> The logs will be sent to the email address `gkowalski@synapse.org`.

**Comment by tschaffter** [comment]
@gkowalski Please review your request. I was thinking that I should clarify how to fill in checkboxes. Also you are asking for the log generated by a tool. This tool can only be of one type (thus the "select one").

**Comment by thomasyu888** [comment]
@gkowalski Your submission ran out of time quota (which is 2 hours...), but it doesn't actually look like your submission ran for that long...  Ill have to look into this, something is fishy about the infra.

**Comment by gkowalski** [comment]
My code is poorly written, loading the nlp model for each request instead of catching it once on startup. Need to work on getting flask to do what I want.

**Comment by gkowalski** [comment]
I've resubmitted the same Docker image again today per @thomasyu888  suggestion. Have not received any feedback other than  the initial email stating "Dear MCW Team: Your submission (submission ID 9712826) is in progress" the logs were produced https://www.synapse.org/#!Synapse:syn26010942  showing no errors ..
