### ISSUE TITLE
The size of the column 'tool__description' is too small. The column size needs to be at least 150 characters.

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/support#8]
I got this message on the admin dashboard (TEST). The table was fine a few minutes ago, where I had a submission running. Since last time I submitted a tool I changed the description of my tool. Could it be the reason for this error? Note that my tool description now include "special" characters `(`, `)`, and `:`.

Tool description: `Spark NLP-based PHI annotator (NER model: ner_deid_large_en_2.5.3_2.4_1595427435246, embeddings model: embeddings_clinical_en_2.4.0_2.4_1580237286004)`

**Comment by thomasyu888** [comment]
Fixed.

**Comment by tschaffter** [comment]
I confirm that the error is gone. Thanks!
